### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/matrix_creator_ros#1]
Nov 05 01:27:24 matrix sudo[462]: Sound detected! Average energy: 4820005
Nov 05 01:27:34 matrix sudo[462]: Sound detected! Average energy: 4263291
Nov 05 01:27:34 matrix sudo[462]: Sound detected! Average energy: 4509909
Nov 05 01:27:36 matrix sudo[462]: Sound detected! Average energy: 3085586
Nov 05 01:27:37 matrix sudo[462]: Sound detected! Average energy: 4385499
Nov 05 01:27:37 matrix sudo[462]: *** Error in `/home/pi/ros/kinetic/dev/devel/lib/matrix_creator_hal/direction_of_arrival_node': malloc(): memory corruption: 0x00a167e0 ***
Nov 05 01:27:37 matrix sudo[462]: bash: line 1:   792 Aborted                 rosrun matrix_creator_hal direction_of_arrival_node _frequency:=2 _min_count:=4 __ns:=amigo/ssl _frame_id:=amigo/matrix
Nov 05 01:27:37 matrix sudo[462]: pam_unix(sudo:session): session closed for user pi
Nov 05 01:27:37 matrix systemd[1]: matrix_ros.service: main process exited, code=exited, status=134/n/a
Nov 05 01:27:37 matrix systemd[1]: Unit matrix_ros.service entered failed state.

**Comment by reinzor** [comment]
Hmm, dat moet niet.

**Comment by reinzor** [comment]
Could you try removing the `std::cout` and recompile? https://github.com/tue-robotics/matrix_creator_ros/blob/master/matrix_creator_hal/src/direction_of_arrival_node.cpp#L84

**Comment by MatthijsBurgh** [comment]
Dat zal ik van de week proberen. Helaas vandaag niet meer.

**Comment by reinzor** [comment]
Should be solved; wrong arguments / node in systemd service.
